/// Flutter icons TestIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    
///
/// 
///
import 'package:flutter/widgets.dart';

class TestIcons {
  TestIcons._();

  static const _kFontFam = 'TestIcons';

  static const IconData objective = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData descriptive = const IconData(0xe80b, fontFamily: _kFontFam);
}
