/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      
///
/// 
///
import 'package:flutter/widgets.dart';

class TuitionDetailIcons {
  TuitionDetailIcons._();

  static const _kFontFam = 'TuitionDetailIcons';

  static const IconData alarm_clock = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData test = const IconData(0xe809, fontFamily: _kFontFam);
}
